### ISSUE TITLE
Remove 

### ISSUE THREAD

**Issue by ashleyhood** [TheFox/smtpd#7]
There are some composer packages that are not needed if you want to use this as just a library.

I am suggesting to remove `/src/TheFox/Console` and the following composer packages:

``` json
"symfony/console": "~2.5",
"symfony/filesystem": "~2.5",
"liip/process-manager": "~1.0"
```

Also `phpmailer/phpmailer` should be moved into _require-dev_ in composer.json

My reason behind this is that I'm using an updated version of the Symfony components and this is causing a conflict.

I'm happy to create a pull request for this but wanted to check that this change would be feasible or even desirable.

I realise that this would be a major change and a lot of code would be removed but I would rather not have an incompatible fork.

**Comment by TheFox** [comment]
Yeah, sure! Do it. ;) The reason why I added `/src/TheFox/Console` is because of the [Stand-alone server](https://github.com/TheFox/smtpd#stand-alone-server). But this of course is only for testing purposes and not needed by production systems. Maybe I'll make a separate repository for that. PHPMailer is only used in example.php, so move it.
